project 'EPUB_FolioReader.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EPUB_FolioReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EPUB_FolioReader
  pod 'GCDWebServer/WebUploader'
end
